### ISSUE TITLE
더미 데이터 등록

### ISSUE THREAD

**Issue by im-gnar** [sgs-ncns/NCNS-Server#16]
## 💫  Description

더미데이터 등록

## 🌈  Task List

- [ ] 유저 데이터 등록
- [ ] 게시글 데이터 등록
- [ ] 댓글 데이터 등록
- [ ] 팔로우 데이터 등록
- [ ] 좋아요 데이터 등록
- [ ] 태그 데이터 등록

## 🌟  Consideration

- ooo
