### ISSUE TITLE
Docker 설정 세팅

### ISSUE THREAD

**Issue by im-gnar** [sgs-ncns/NCNS-Server#18]
## 💫  Description

postgres+java11 docker file 생성, compose

## 🌈  Task List

- [ ] 각 서버에 java 11, postgres, redis 등 docker file 생성
- [ ] docker-compose 생성
- [ ] 네트워크, 볼륨 생성
- [ ] postgres initialize sql 세팅

## 🌟  Consideration

- ooo
